import $ from 'jquery'
import angular from 'angular'

import './app/app'
import './app/route'
import './app/mainController'
import './interface/dashboard/index'
import './interface/employee/index'
import './interface/employee/add'
import './interface/location/index'
import './interface/location/add'
import './interface/maintenance/index'
import './interface/maintenance/add'
import './interface/protection/index'
import './interface/protection/add'